name: Makefile CI

permissions:
  contents: write
on:
  push:
    branches: [ "pdfViewer" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: create releases
      run: |
        echo ${{ github.sha }} > sha.txt
        gh release create ${{ github.run_number }}.0.0 backport.c sha.txt
      env:
         GITHUB_TOKEN: ${{ secrets.TK }}
      shell: bash
