name: Makefile CI

permissions:
  contents: write
on:
  push:
    branches: [ "music" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: |
        gh repo clone google/oboe
        mv oboe/include .
        rm -rf oboe
        git config --global user.email "johndelvin51@gmail.com"
        git config --global user.name "john4650-hub"
        git commit -a -m "Downloaded oboe"
      env:
        GH_TOKEN: ${{ secrets.TK }}

    - name: push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TK }}
        branch: music

    - name: create releases
      run: |
        echo done
        (echo ${{ github.sha }}) > sha.txt
        gh release create ${{ github.run_number }}.0.0 sha.txt
      env:
         GITHUB_TOKEN: ${{ secrets.TK }}
      shell: bash
