name: Makefile CI
permissions:
  contents: write
on:
  push:
    branches: [ "main" ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: |
        echo done
        ${{ github.sha }} > sha.txt
        gh release create ${{ github.run_number }}.0.0 sha.txt
      env:
         GITHUB_TOKEN: ${{ secrets.TK }}
      shell: bash
