name: Makefile CI

permissions:
  contents: write
on:
  push:
    branches: [ "music" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: create releases
      run: |
        sudo apt-get install findutils
        find . -name "*.cpp" -o -name "*.hpp" -exec clang-format -i {}
        echo done
        (echo ${{ github.sha }}) > sha.txt
        zip -r formatted_files.zip $(find . -name "*.cpp" -o -name "*.hpp")
        gh release create ${{ github.run_number }}.0.0 sha.txt formatted_files.zip
      env:
         GITHUB_TOKEN: ${{ secrets.TK }}
      shell: bash
