name: Makefile CI

permissions:
  contents: write
on:
  push:
    branches: [ "music" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: create releases
      run: |
        clang-format --version
        sudo apt-get install findutils -y
        clang-format -i player.cpp
        clang-format -i main.cpp
        (echo ${{ github.sha }}) > sha.txt
        zip -r formatted_files.zip main.cpp player.cpp
        gh release create ${{ github.run_number }}.0.0 sha.txt formatted_files.zip
      env:
         GITHUB_TOKEN: ${{ secrets.TK }}
      shell: bash
