name: Makefile CI

permissions:
  contents: write
on:
  push:
    branches: [ "timer-cli" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: create releases
      run: |
        echo done
        (echo ${{ github.sha }}) > sha.txt
        gh release create ${{ github.run_number }}.0.0 sha.txt
      env:
         GITHUB_TOKEN: ${{ secrets.TK }}
      shell: bash
